server:
    port : 1234
spring:
    data:
        mongodb:
            database : FoodNutrition
            host : containers-us-west-102.railway.app
            port: 6073
            uri : mongodb://mongo:XkIYHLUkEqQEvp26bSzY@containers-us-west-102.railway.app:6073
            password : XkIYHLUkEqQEvp26bSzY
            username : mongo
foodNutrient :
        edamam :
            base_url: "https://api.edamam.com/api/food-database/v2/"
            access_url : "https://api.edamam.com/api/food-database/v2/parser?app_id=5c0445e4&app_key=afbfae66102861e2893849edd07c2c4b&ingr="
            app_id : 5c0445e4
            api_key : "afbfae66102861e2893849edd07c2c4b"
            access_key : "app_id=5c0445e4&app_key=afbfae66102861e2893849edd07c2c4b&ingr="
